### ISSUE TITLE
Release checklist v0.11.0

### ISSUE THREAD

**Issue by ckadner** [kserve/modelmesh-serving#365]
#### Pre-release work items:

- [ ] wait for [`v0.11.0-rc0`](https://github.com/kserve/kserve/releases/tag/v0.11.0-rc0) [`kserve/kserve` release candidate](https://github.com/kserve/kserve/releases) and prepare release according to the [ModelMesh release process](https://github.com/kserve/modelmesh-serving/blob/main/docs/release-process.md)
- [ ] ...

#### Post-release work items:

- [ ]  update Quickstart Guide with instructions that [changed in `v0.11.0`](https://github.com/kserve/modelmesh-serving/compare/v0.10.0..main#diff-988a5392cf907f7c5728b8ac90445facc7f835f3c00375764ec99769dcde2d5a)
  - [ ] https://github.com/kserve/modelmesh-serving/pull/364 (https://github.com/kserve/modelmesh-serving/pull/342)
- [ ] ...
