### ISSUE TITLE
ModelMesh Release Tracker for KServe v0.7.0

### ISSUE THREAD

**Issue by pvaneck** [kserve/modelmesh-serving#37]
The plan is to cut the KServe 0.7 release mid next week. For this release, ModelMesh will be loosely integrated with KServe.

Action Items:

- [x] ModelMesh InferenceService CRD Support
  - [x] https://github.com/kserve/modelmesh-serving/pull/34
  - [x] Documentation on using InferenceService CR with ModelMesh
    - https://github.com/kserve/modelmesh-serving/pull/47
- [x] ModelMesh REST Proxy Sidecar Support
  - [x] https://github.com/kserve/modelmesh-serving/pull/27 
  - [x] Documentation on using REST inferencing
- [x] Add KServe ModelMesh DeploymentMode Annotation checker
  - https://github.com/kserve/kserve/pull/1851
- [ ] Update KServe `hack/quick_install.sh` to include ModelMesh-Serving as part of installation.
  - https://github.com/kserve/kserve/pull/1844
- [x] Documentation updates
  - [x] Refresh External ModelMesh Documentation
    - https://github.com/kserve/modelmesh-serving/pull/39
  - [x] Update KServe Website with ModelMesh Documentation 
    - https://github.com/kserve/website/issues/17
    - Can view website here: https://kserve.github.io/website/
    - https://github.com/kserve/website/pull/32
    - https://github.com/kserve/website/pull/37
- [x] Assemble release process items
    - Tag release for version `v0.7.0` to follow suit with KServe.
    - [x] GitHub workflow for tagged release
    - [x] Release process documentation
      - Create document outline process of creating a release branch and tagging from commit in that branch. KServe should already have document like this.
      - https://github.com/kserve/modelmesh-serving/pull/40
      - https://github.com/kserve/modelmesh/pull/7
      - https://github.com/kserve/modelmesh-runtime-adapter/pull/7

**Comment by pvaneck** [comment]
@ScrapCodes Have you had a chance to revisit https://github.com/kserve/kserve-pending/pull/54 ? Looks like it needs to be reopened in `kserve/kserve`.

**Comment by chinhuang007** [comment]
I suggest we make modelmesh-serving release v0.7.0 to be in sync with KServe

**Comment by pvaneck** [comment]
@yuzisun With the KServe website being introduced, what is the future of the KServe `docs` folder? Should MMS docs in this folder be updated there as well as on the website? And will the main KServe README still contain install instructions (like it does currently) or will we switch it to link to the install page on the website?

**Comment by ScrapCodes** [comment]
Hi @pvaneck, I was trying a different approach for it. Similar to https://github.com/kserve/kserve-pending/pull/57 . Once it is ready, I will open it against kserve/kserve.

**Comment by pvaneck** [comment]
Thanks, @ScrapCodes . Let me know if you are encountering any issues, or need any help. The aim is to get this in before the KServe release is cut Wednesday next week.

**Comment by ScrapCodes** [comment]
Thanks @pvaneck , I have an open PR https://github.com/kserve/kserve/pull/1851.
